### ISSUE TITLE
Usage of branches

### ISSUE THREAD

**Issue by MaxZhaloba** [ros-ukraine/leobot#24]
I'm rather new to GitHub so I wanted to ask for advice on branching and merging of project code.

I've performed such steps:

1. Created a branch `F#16_web_server` for the task "Create web package #16"
2. Added some preliminary code to this branch (empty package)
3. Created a pull request for this code
4. @AndriyPt merged it into the default branch and closed the pull request. When I open the pull request page on GitHub it suggests to delete this branch but so far it remains in the repository.

Next thing I'm going to add more code to implement this issue.

Could you please help me with such questions:
1. Should I delete the branch `F#16_web_server` as suggested by GitHub and create a new one with further commits for this task?
2. Should I create another pull request when I finish this task?

Thanks :)
Max

**Comment by AndriyPt** [comment]
@MaxZhaloba nice place to ask questions :+1: 
I have intentionally left your branch after merging Pull Request.
Since I knew that you will proceed working on your issue and you are new to GitHub :)
So you can continue working in your branch.
But in general I am deleting branches after merging PR and you need to create F#16_create_package_skeleton first after that F#16_implement_web_package. 
In last PR I will use phrase in descriptions "Closes # 16" and it will automatically close issue #16 after PR is merged :)
But for now please proceed in your current branch ;)

**Comment by MaxZhaloba** [comment]
Thanks :)
