### ISSUE TITLE
Add teleoperation from web page

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#51]

**Comment by MaxZhaloba** [comment]
@AndriyPt, I'm considering adding jQuery to our web page to make it easier to listen to button and keyboard pressing. It will make a significant difference for our current and future JS code. Otherwise we'll end up writing all our browser code in plain vanilla JS, as it's done now. What's your opinion of this?

**Comment by AndriyPt** [comment]
@MaxZhaloba feel free to add. My only concern is that web page should work in LAN without Internet so all resource should be local not downloaded every time the page is reloaded :)
